-- TRAVEL 테이블이 없는 경우를 위한 생성 (기존 TRAVELPLAN과 별도)
CREATE TABLE IF NOT EXISTS TRAVEL (
    TRAVEL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    DESTINATION VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DESCRIPTION TEXT,
    MAX_PARTICIPANTS INT DEFAULT 10,
    PARTICIPANT_COUNT INT DEFAULT 0,
    MBTI_TYPE VARCHAR(4),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRAVEL_USER FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);

-- 여행 계획 참여자 테이블 생성 (TRAVELPLAN의 ID를 참조)
DROP TABLE IF EXISTS TRAVEL_PARTICIPANTS;
CREATE TABLE TRAVEL_PARTICIPANTS (
    PARTICIPANT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRAVEL_ID BIGINT NOT NULL COMMENT '여행 계획 ID (TRAVELPLAN의 PLAN_ID 참조)',
    USER_ID VARCHAR(50) NOT NULL,
    JOINED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT FK_PARTICIPANT_PLAN FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVELPLAN(PLAN_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ID_PARTICIPANT FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT UK_TRAVEL_USER UNIQUE KEY (TRAVEL_ID, USER_ID)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_PARTICIPANT_USER ON TRAVEL_PARTICIPANTS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_PARTICIPANT_TRAVEL ON TRAVEL_PARTICIPANTS(TRAVEL_ID);

-- 샘플 데이터 (테스트용)
INSERT IGNORE INTO TRAVEL (USER_ID, TITLE, DESTINATION, START_DATE, END_DATE, DESCRIPTION, MAX_PARTICIPANTS, MBTI_TYPE) VALUES
('admin', '제주도 힐링 여행', '제주도', '2024-12-01', '2024-12-03', '제주도에서 힐링하는 2박 3일 여행입니다.', 4, 'INFP'),
('admin', '부산 맛집 투어', '부산', '2024-12-10', '2024-12-12', '부산의 유명 맛집들을 탐방하는 여행입니다.', 6, 'ESFP'),
('admin', '서울 문화 탐방', '서울', '2024-12-15', '2024-12-17', '서울의 역사와 문화를 탐방하는 여행입니다.', 5, 'ENFJ');