-- 여행 계획 테이블 생성
CREATE TABLE IF NOT EXISTS TRAVEL (
    TRAVEL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    DESTINATION VARCHAR(100) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    DESCRIPTION TEXT,
    MAX_PARTICIPANTS INT DEFAULT 10,
    PARTICIPANT_COUNT INT DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRAVEL_USER FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX IDX_TRAVEL_USER ON TRAVEL(USER_ID);
CREATE INDEX IDX_TRAVEL_STATUS ON TRAVEL(STATUS);
CREATE INDEX IDX_TRAVEL_DESTINATION ON TRAVEL(DESTINATION);