-- 여행 계획 참여자 테이블 생성
CREATE TABLE IF NOT EXISTS TRAVEL_PARTICIPANTS (
    PARTICIPANT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRAVEL_ID BIGINT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    JOINED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT FK_TRAVEL_ID FOREIGN KEY (TRAVEL_ID) REFERENCES TRAVEL(TRAVEL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ID_PARTICIPANT FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT UK_TRAVEL_USER UNIQUE KEY (TRAVEL_ID, USER_ID)
);

-- 인덱스 생성
CREATE INDEX IDX_PARTICIPANT_USER ON TRAVEL_PARTICIPANTS(USER_ID);
CREATE INDEX IDX_PARTICIPANT_TRAVEL ON TRAVEL_PARTICIPANTS(TRAVEL_ID);

-- 여행 테이블에 참여자 수 컬럼 추가 (없는 경우)
ALTER TABLE TRAVEL ADD COLUMN IF NOT EXISTS PARTICIPANT_COUNT INT DEFAULT 0;